### ISSUE TITLE
Minimal Symfony Version should be 2.6

### ISSUE THREAD

**Issue by dritter** [gomeeki/url-shortener-bundle#6]
Hi!

This bundle uses the `factory` tag in `Resources/config/services.xml`, which was introduced in symfony 2.6 (see https://github.com/symfony/symfony/commit/bd8531d2d893d154f2f639657afa828254c52d97 ).

So, there are two ways of solving this:
1. Update the minimal symfony version to 2.6
2. Use the deprecated `factory-method` and `factory-service` attributes on the `service` tag. This should be done on a separate branch, IMHO.

**Comment by jojoee** [comment]
Hi @dritter
You're right, thank you for suggestion :)
ref: http://symfony.com/doc/2.7/service_container/factories.html
